# SPDX-License-Identifier: MIT
name: CI

on:
  push:
    branches:
    - master
    - feature/**
    - dependabot/**
    paths-ignore:
    - '**.md'
    - '.gitignore'

env:
  TASK_VERSION: 2.8.0

jobs:
  docker-hub:
    runs-on: ubuntu-20.04
    steps:
    - name: Set up task
      run: |
        sudo bash -c 'curl -fsSL https://taskfile.dev/install.sh | bash -s -- -b /usr/local/bin v${{ env.TASK_VERSION }}'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        task docker:build
    - name: Test
      run: |
        task docker:test
